<a href="https://colab.research.google.com/github/syedanoshin/Numpy-Main-Project/blob/main/KAG_conversion_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data_path="/content/drive/MyDrive/KAG_Conversion_Data.csv"



In [3]:
data1 =pd.read_csv(data_path)

In [4]:
data1.head()

ad_id  xyz_campaign_id  fb_campaign_id    age gender  interest  \
0  708746              916          103916  30-34      M        15   
1  708749              916          103917  30-34      M        16   
2  708771              916          103920  30-34      M        20   
3  708815              916          103928  30-34      M        28   
4  708818              916          103928  30-34      M        28   

   Impressions  Clicks  Spent  Total_Conversion  Approved_Conversion  
0         7350       1   1.43                 2                    1  
1        17861       2   1.82                 2                    0  
2          693       0   0.00                 1                    0  
3         4259       1   1.25                 1                    0  
4         4133       1   1.29                 1                    1

In [9]:
from pandas.core.arrays.sparse import dtype
data_str = np.genfromtxt(data_path, delimiter=",", skip_header=1,dtype=str)
#data = np.genfromtxt(data_path, delimiter=",", skip_header=1)

# printing the data
data = np.genfromtxt(data_path,delimiter= ',',skip_header=1,dtype=float)

print("\nData: \n\n", data)
print(data.shape)



Data: 

 [[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]
(1143, 11)


In [10]:
data_str

array([['708746', '916', '103916', ..., '1.429999948', '2', '1'],
       ['708749', '916', '103917', ..., '1.820000023', '2', '0'],
       ['708771', '916', '103920', ..., '0', '1', '0'],
       ...,
       ['1314412', '1178', '179979', ..., '40.28999949', '2', '0'],
       ['1314414', '1178', '179981', ..., '198.7100005', '8', '2'],
       ['1314415', '1178', '179982', ..., '165.6099987', '5', '2']],
      dtype='<U11')

In [11]:
xyzcampaignid=np.array(data[:,1])
print(xyzcampaignid)
print(np.unique(xyzcampaignid))
count = xyzcampaignid[xyzcampaignid==916.].shape[0]
print(count)
count = xyzcampaignid[xyzcampaignid==936.].shape[0]
print(count)
count = xyzcampaignid[xyzcampaignid==1178.].shape[0]
print(count)


[ 916.  916.  916. ... 1178. 1178. 1178.]
[ 916.  936. 1178.]
54
464
625


In [13]:
age_group=data_str[:,3]
print(age_group)
print(np.unique(age_group))

['30-34' '30-34' '30-34' ... '45-49' '45-49' '45-49']
['30-34' '35-39' '40-44' '45-49']


In [14]:
spends = data[:,8]
avg_spends = spends.mean()
min_spends = spends.min()
max_spends = spends.max()
print('Average spends on ads = ',avg_spends)
print('Minimum spends on ads = ',min_spends)
print('Maximum spends on ads = ',max_spends)


Average spends on ads =  51.36065613141295
Minimum spends on ads =  0.0
Maximum spends on ads =  639.9499981


In [15]:
clk =data[:,7]
print(clk.max())



421.0


In [16]:
id = data[:,0]
id_max_clicked = id[clk==clk.max()]
id_max_clicked

array([1121814.])

In [17]:
ap_conv= data[:,10]
print(ap_conv[clk==clk.max()])

[13.]


In [18]:
print(ap_conv.max())

21.0


In [19]:
print(data[ap_conv==ap_conv.max()])

[[1.12110400e+06 1.17800000e+03 1.44533000e+05            nan
             nan 1.60000000e+01 2.08066600e+06 2.02000000e+02
  3.60150001e+02 4.00000000e+01 2.10000000e+01]]


In [20]:
print(data_str[ap_conv==ap_conv.max()])

[['1121104' '1178' '144533' '30-34' 'M' '16' '2080666' '202'
  '360.1500015' '40' '21']]
